apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-taint-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: node-taint-controller
    app.kubernetes.io/component: controller
