apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-taint-controller
spec:
  template:
    spec:
      containers:
        - name: controller
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
