apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-taint-controller.fullname" . }}-config
  namespace: {{ include "node-taint-controller.namespace" . }}
  labels:
    {{- include "node-taint-controller.labels" . | nindent 4 }}
data:
  unhealthy-delay-minutes: {{ .Values.config.unhealthyDelayMinutes | quote }}
  recovery-delay-minutes: {{ .Values.config.recoveryDelayMinutes | quote }}
  max-unhealthy-percentage: {{ .Values.config.maxUnhealthyPercentage | quote }}
  node-label-selector: {{ .Values.config.nodeLabelSelector | quote }}
