apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-taint-controller.fullname" . }}
  namespace: {{ include "node-taint-controller.namespace" . }}
  labels:
    {{- include "node-taint-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    {{- include "node-taint-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ trimPrefix ":" .Values.controller.metricsBindAddress }}
      targetPort: metrics
      protocol: TCP
